services:
  picmd:
    image: ghcr.io/asano69/picmd:latest
    container_name: picmd
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - picmd.env
    volumes:
      - ./data:/picmd/data
        #- /etc/ssl/certs/root_ca.crt:/certs/root_ca.crt:ro # optional
    environment:
      - TZ=Europe/London
      #
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      #networks:
    #  - traefik_net
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.picmd.rule=Host(`picmd.app.internal`)
#volumes:
#  data:

#networks:
#  traefik_net:
#    external: true

